### ISSUE TITLE
New script

### ISSUE THREAD

**Issue by sbraitti** [seefor/awesome-infoblox#3]
Hi, 
Thank you all for sharing these scripts. 

I've created a new script to compare zone records from two different nameservers trough Zone Transfer (eg: Microsoft DNS and B1DDI OnPrem) and then modify B1DDI to synchronize those records. 
If you think it is interesting, you can add to your list =) 

I made that for a customer that is migrating from Microsoft DNS to B1DDI but doesn't want to make a hard swap in their environment. 
Please, feel free to make your comments and suggestions. 

https://github.com/sbraitti/sync-b1ddi - My repo

**Comment by seefor** [comment]
I do thank for you this :)
